name: "Terratest GitHub Action"
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_REGION: "us-east-1"
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.21)
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go
      - name: Run 'go test -v -timeout 30m'
        run: |
          cd test
          go mod download
          go test -v -timeout 30m
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
